services:
  old-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=rubygems_master
      - POSTGRES_DB=rubygems_development
      - POSTGRES_PASSWORD=randompass-old
    networks:
      - db
    ports:
      - 5555:5555
    volumes:
      - "./configs/postgres.old.conf:/postgres.conf:z"
    command: postgres -c 'config_file=/postgres.conf'
  new-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=rubygems_master
      - POSTGRES_DB=rubygems_development
      - POSTGRES_PASSWORD=randompass-new
    networks:
      - db
    ports:
      - 5556:5556
    volumes:
      - "./configs/postgres.new.conf:/postgres.conf:z"
    command: postgres -c 'config_file=/postgres.conf'
networks:
  db:
