apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
spec:
  selector:
    app: pgbouncer
  ports:
    - protocol: TCP
      port: 5557
      targetPort: 5557
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: public.ecr.aws/docker/library/debian:12
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c", "--" ]
          args:
            - |
              apt-get update && \
              apt-get install -y postgresql-client pgbouncer vim git procps pspg && \
              git clone https://github.com/rubygems/pg-major-update.git && \

              cd pg-major-update && \
          ports:
            - containerPort: 5557
